ResearchManagementSystem/Areas/CreSys/Models/Faculty.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace CRE.Models
{
    public class Faculty
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int facultyId { get; set; }
        public string userId { get; set; }
        public string Name {  get; set; }
        [Required]
        public string? userType { get; set; }
        [Required]
        public int? salaryGrade { get; set; }


        //navigation properties
        public Chairperson Chairperson { get; set; }
        public EthicsEvaluator EthicsEvaluator { get; set; }
    }
}

ResearchManagementSystem/Controllers/FacultyController.cs
using Microsoft.AspNetCore.Mvc;

namespace ResearchManagementSystem.Controllers
{
    public class FacultyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        
        public IActionResult FacultyApplication()
        {
            return View();
        }
        public IActionResult FacultyCenters()
        {
            return View();
        }
        public IActionResult FacultyNotifications()
        {
            return View();
        }
        public IActionResult FacultyProfile()
        {
            return View();
        }
        public IActionResult FacultyHelp()
        {
            return View();
        }
        public IActionResult FacultyReportGenerateReport()
        {
            return View();
        }
        public IActionResult FacultyReportGenerateReportPreview()
        {
            return View();
        }
        
        public IActionResult FacultyReportRecentReport()
        {
            return View();
        }
        public IActionResult FacultyReportArchivedReport()
        {
            return View();
        }
        public IActionResult FacultyReportRecentReportPreview()
        {
            return View();
        }
        public IActionResult FacultyReportArchivedReportPreview()
        {
            return View();
        }
        public IActionResult FacultyRateUs()
        {
            return View();
        }
        public IActionResult FacultyAbout()
        {
            return View();
        }
        public IActionResult FacultyAccomplishments()
        {
            return View();
        }

        public IActionResult FacultyCitationView()
        {
            return View();
        }
        public IActionResult FacultyCopyrightView()
        {
            return View();
        }
        public IActionResult FacultyPatentView()
        {
            return View();
        }
        public IActionResult FacultyPresentationView()
        {
            return View();
        }
        public IActionResult FacultyProductionView()
        {
            return View();
        }
        public IActionResult FacultyPublicationView()
        {
            return View();
        }
        public IActionResult FacultyUtilizationView()
        {
            return View();
        }
    }
}

ResearchManagementSystem/Views/Faculty/FacultyCenters.cshtml
@{
    ViewData["Title"] = "Centers";
    Layout = "Faculty_Layout";
}
<link href="~/css/ClusterCoordinator-Centers.css" rel="stylesheet" />
<div>
    <div class="container shadow mt-4" id="main">
        <div class="p-4 display-6 mb-1 row" id="title">
            RMO Centers
        </div>
        <div class="p-4 row text-center" id="centers">
            <a class="rounded-5 p-4 m-3 col-md text-white text-decoration-none fs-5 fw-bold p-3" id="cen" href="@Url.Action("Index", "Home", new {area = "RemcSys"})">
                Research Evaluation and Monitoring Center
            </a>
            <a class="col-md rounded-5 p-4 m-3 text-white text-decoration-none fs-5 fw-bold p-3" id="cen" href="@Url.Action("Index", "Home", new {area = "RscSys"})">
                Research Support Center
            </a>
            <a class="col-md rounded-5 p-4 m-3 text-white text-decoration-none fs-5 fw-bold p-3" id="cen" href="@Url.Action("Index", "Home", new {area = "CreSys"})">
                Center for Research Ethics
            </a>
            <a class="col-md rounded-5 p-4 m-3 text-white text-decoration-none fs-5 fw-bold p-3" id="cen" href="#">
                Center for Research Dissemination and Linkages
            </a>
        </div>
    </div>

</div>

ResearchManagementSystem/Views/Faculty/FacultyCitationView.cshtml
@{
    ViewData["Title"] = "Accomplishments";
    Layout = "Faculty_Layout";
}
<link href="~/css/ClusterCoordinator-Accomplishmentdetails.css" rel="stylesheet" />

<div>

    <div class="container shadow mb-3" id="content">
        <div class="row shadow-sm h3 p-4 mb-1" id="title">
            <div class="d-flex justify-content-between">
                <div>Citation Details</div>

            </div>
        </div>
        <div class="row shadow p-4" id="formcont">
            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Title of (Original) Research Article:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Title of (Original) Research Article</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of (Original) Article 1:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of (Original) Article 1</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of (Original) Article 2:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of (Original) Article 2</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of (Original) Article 3:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of (Original) Article 3</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of (Original) Article 4:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of (Original) Article 4</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of (Original) Article 5:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of (Original) Article 5</p>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-lg-3 col-sm-12">
                    <strong>Title of Refereed Journal Where the (Original) Research Article Was Published:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Title of Refereed Journal Where the (Original) Research Article Was Published</p>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-lg-3 col-sm-12">
                    <strong>Title of (New) Publication Where the (Original) Research Article Was Cited:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Title of (New) Publication Where the (Original) Research Article Was Cited</p>
                </div>
            </div>


            <div class="row mb-3">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of the (New) Article Who Cited the (Original) Research Article 1:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of the (New) Article Who Cited the (Original) Research Article 1</p>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of the (New) Article Who Cited the (Original) Research Article 2:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of the (New) Article Who Cited the (Original) Research Article 2</p>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of the (New) Article Who Cited the (Original) Research Article 3:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of the (New) Article Who Cited the (Original) Research Article 3</p>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of the (New) Article Who Cited the (Original) Research Article 4:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of the (New) Article Who Cited the (Original) Research Article 4</p>
                </div>
            </div>
            <div class="row mb-3">
                <div class="col-lg-3 col-sm-12">
                    <strong>Author/s of the (New) Article Who Cited the (Original) Research Article 5:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Author/s of the (New) Article Who Cited the (Original) Research Article 5</p>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-lg-3 col-sm-12">
                    <strong>Title of Refereed Journal Where the (New) Research Article Was Published:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Title of Refereed Journal Where the (New) Research Article Was Published</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Volume No./Issue No.:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Volume No./Issue No.</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>No. of Pages:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>No. of Pages</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Year of Publication:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Year of Publication</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Indexing:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p>Indexing</p>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-3 col-sm-12">
                    <strong>Proof:</strong>
                </div>
                <div class="col-lg-9 col-sm-12">
                    <p><button type="button" class="btn btn-danger btn-sm me-2">Proof.pdf</button></p>
                </div>
            </div>
        </div>
    </div>

    <!--delete modal-->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content rounded-4" id="bgmodal">
                <div class="modal-body rounded-4 p-4">
                    <h2 class="text-center mb-4" id="modaltitle">Delete Citation Details</h2>
                    <p id="content">Are you sure you want to delete the citation details for research titled "[Research Title]"?</p>
                    <strong id="content">This action cannot be undone.</strong>
                    <div class="mt-4 d-flex justify-content-center align-items-center">
                        <button type="button" class="me-2" data-bs-dismiss="modal" id="modalbtn">Close</button>
                        <button type="button" class="me-2" data-bs-dismiss="modal" id="modalbtn">Confirm</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

ResearchManagementSystem/Views/Faculty/FacultyReportArchivedReport.cshtml
@{
    ViewData["Title"] = "Report";
    Layout = "Faculty_Layout";
}
<link href="~/css/ClusterCoordinator-Report-GenerateReport.css" rel="stylesheet" />
<style>
    /*tables*/
    #tbl {
        border-radius: 20px;
    }

    #action {
        border: none;
        background: none;
        border-radius: 10px;
        padding: 10px;
    }

        #action:hover {
            background: rgb(133, 0, 0, 0.2);
        }

    #content {
        font-family: "Inter";
        color: black;
    }

    th {
        font-family: "Montserrat";
        color: black;
    }

    td {
        color: black;
        font-family: "Inter";
    }

    table th, table td {
        white-space: nowrap;
    }

    table td {
        min-width: 100px;
    }

    .modal-body {
        border: 4px solid #850000;
    }

    #modaltitle {
        color: #850000;
        font-family: "Poppins";
        font-weight: bold;
    }

    #modalbtn {
        background: #850000;
        border-radius: 15px;
        height: 50px;
        padding: 0px 30px;
        color: white;
        font-family: "Inter";
        font-size: 20px;
        border: none;
        outline: none;
        box-shadow: 2px 5px 5px rgb(0, 0, 0, 0.10), -2px 5px 5px rgb(0, 0, 0, 0.10);
        transition: ease-in-out .1s
    }

        #modalbtn:hover {
            background: #560000;
        }
</style>
<div>
    <!--navbar-->
    <div class="nnvb container mt-3 mb-3">
        <div class="row">
            <div class="itm col-lg-2 col-sm-12 me-2 p-1 mb-1 text-center">
                <a class="text-decoration-none" asp-controller="Faculty" asp-action="FacultyReportGenerateReport" id="inaactive">Generate Report</a>
            </div>
            <div class="itm col-lg-2 col-sm-12 me-2 p-1 mb-1 text-center">
                <a class="text-decoration-none" asp-controller="Faculty" asp-action="FacultyReportRecentReport" id="inaactive">Recent Report</a>
            </div>
            <div class="itm-active col-lg-2 col-sm-12 me-2 p-1 mb-1 text-center">
                <a class="text-decoration-none" asp-controller="Faculty" asp-action="FacultyReportArchivedReport" id="aactive">Archived Report</a>
            </div>
        </div>
    </div>
    <!--search and filter-->
    <div class="container mt-3">
        <div class="row justify-content-between">
            <!--search-->
            <div class="col-lg-3 col-sm-12 mb-2">
                <form action="" class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search">
                    <button type="submit" id="action"><i class="fa-solid fa-magnifying-glass fa-2xl" style="color: #850000;"></i></button>
                </form>
            </div>
            <!--filter-->
            <div class="col-lg-3 col-sm-12 mb-2">
                <form action="" class="d-flex">
                    <div class="dropdown w-100">
                        <button class="btn btn-danger dropdown-toggle w-100 d-flex justify-content-between align-items-center" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Filter
                        </button>
                        <div class="dropdown-menu w-100">
                            <div class="container">

                                <div class="row mb-1">
                                    <div class="col-lg-12">
                                        <strong>Report Name</strong>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-lg-12">
                                        <select id="filterSelect" class="form-select me-2">
                                            <option>Report Name (A-Z)</option>
                                            <option>Report Name (Z-A)</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="row mb-1">
                                    <div class="col-lg-12">
                                        <strong>Report Type</strong>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-lg-12">
                                        <select id="filterSelect" class="form-select me-2">
                                            <option>Production</option>
                                            <option>Presentation</option>
                                            <option>Publication</option>
                                            <option>Utilization</option>
                                            <option>Patent</option>
                                            <option>Citation</option>
                                            <option>Copyright</option>
                                        </select>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-lg-12">
                                        <strong>Scope</strong>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-lg-6">
                                        <label class="form-label" for="start_date">Start Date</label>
                                        <input class="form-control form-control-sm me-2" type="date" id="start_date">
                                    </div>
                                    <div class="col-lg-6">
                                        <label class="form-label" for="end_date">End Date</label>
                                        <input class="form-control form-control-sm me-2" type="date" id="end_date">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12">
                                        <strong>Date Generated</strong>
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-lg-12">
                                        <label class="form-label" for="date_generated">Date Generated</label>
                                        <input class="form-control form-control-sm me-2" type="date" id="date_generated">
                                    </div>
                                </div>
                                <div class="row mb-1">
                                    <div class="col-lg-12">
                                        <button type="button" class="btn btn-danger w-100">Apply Filter</button>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--table-->
    <div class="container bg-white shadow mt-1 table-responsive rounded-4 p-0">
        <table class="table table-borderless w-100">
            <thead class="shadow-sm">
                <tr class="align-middle">
                    <th class="p-4 bg-transparent" scope="row">Report Name</th>
                    <th class="p-4 bg-transparent" scope="row">Report Type</th>
                    <th class="p-4 bg-transparent" scope="col">Scope</th>
                    <th class="p-4 bg-transparent" scope="col">Date Generated</th>
                    <th class="p-4 bg-transparent" scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                <tr class="align-middle">
                    <td class="p-4 bg-transparent" scope="row">Report Name</td>
                    <td class="p-4 bg-transparent" scope="row">Report Type</td>
                    <td class="p-4 bg-transparent" scope="col">Scope</td>
                    <td class="p-4 bg-transparent" scope="col">Date Generated</td>
                    <td class="p-4 bg-transparent" scope="col">
                        <button id="action" class="me-2"><a asp-controller="Faculty" asp-action="FacultyReportArchivedReportPreview"><i class="fa-solid fa-eye fa-2xl" style="color: #850000;"></i></a></button>
                        <button id="action" data-bs-toggle="modal" data-bs-target="#staticBackdrop2" class="me-2"><i class="fa-solid fa-download fa-2xl" style="color: #850000;"></i></button>
                        <button id="action" data-bs-toggle="modal" data-bs-target="#staticBackdrop"><i class="fa-solid fa-trash fa-2xl" style="color: #850000;"></i></button>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    <!--delete modal-->
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content rounded-4" id="bgmodal">
                <div class="modal-body rounded-4 p-4">
                    <h2 class="text-center mb-4" id="modaltitle">Delete Report</h2>
                    <p id="content">Are you sure you want to delete the report named "[Report Name]"?</p>
                    <strong id="content">This action cannot be undone.</strong>
                    <div class="mt-4 d-flex justify-content-center align-items-center">
                        <button type="button" class="me-2" data-bs-dismiss="modal" id="modalbtn">Close</button>
                        <button type="button" class="me-2" data-bs-dismiss="modal" id="modalbtn">Confirm</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--downloaded modal-->
    <div class="modal fade" id="staticBackdrop2" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content rounded-4" id="bgmodal">
                <div class="modal-body rounded-4 p-4">
                    <h2 class="text-center mb-4" id="modaltitle">Report Downloaded</h2>
                    <p id="content">The report named "[Report Name]" has been successfully downloaded.</p>
                    <div class="mt-4 d-flex justify-content-center align-items-center">
                        <button type="button" class="me-2" data-bs-dismiss="modal" id="modalbtn">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

ResearchManagementSystem/Views/Faculty/FacultyReportGenerateReport.cshtml
@{
    ViewData["Title"] = "Report";
    Layout = "Faculty_Layout";
}
<link href="~/css/ClusterCoordinator-Report-GenerateReport.css" rel="stylesheet" />
<div>
    <!--navbar-->
    <div class="nnvb container mt-3 mb-3">
        <div class="row">
            <div class="itm-active col-lg-2 col-sm-12 me-2 p-1 mb-1 text-center">
                <a class="text-decoration-none" asp-controller="Faculty" asp-action="FacultyReportGenerateReport" id="aactive">Generate Report</a>
            </div>
            <div class="itm col-lg-2 col-sm-12 me-2 p-1 mb-1 text-center">
                <a class="text-decoration-none" asp-controller="Faculty" asp-action="FacultyReportRecentReport" id="inaactive">Recent Report</a>
            </div>
            <div class="itm col-lg-2 col-sm-12 me-2 p-1 mb-1 text-center">
                <a class="text-decoration-none" asp-controller="Faculty" asp-action="FacultyReportArchivedReport" id="inaactive">Archived Report</a>
            </div>
        </div>
    </div>
    <!--input fields-->
    <form action="" class="container">
        <div class="container shadow h4 p-4 mb-3" id="title">
            Select Report Type
        </div>

        <label class="form-check-label p-3 mb-2" for="production" id="smaller-container">
            <div class="container d-flex justify-content-between">
                <div class="ppp">Production</div>
                <input class="form-check-input" type="radio" name="reports" id="production">
            </div>
        </label>
        <label class="form-check-label p-3 mb-2" for="presentation" id="smaller-container">
            <div class="container  d-flex justify-content-between">
                <div class="ppp">Presentation</div>
                <input class="form-check-input" type="radio" name="reports" id="presentation">
            </div>
        </label>
        <label class="form-check-label p-3 mb-2" for="publication" id="smaller-container">
            <div class="container  d-flex justify-content-between">
                <div class="ppp">Publication</div>
                <input class="form-check-input" type="radio" name="reports" id="publication">
            </div>
        </label>

        <label class="form-check-label p-3 mb-2" for="utilization" id="smaller-container">
            <div class="container  d-flex justify-content-between">
                <div class="ppp">Utilization</div>
                <input class="form-check-input" type="radio" name="reports" id="utilization">
            </div>
        </label>
        <label class="form-check-label p-3 mb-2" for="patent" id="smaller-container">
            <div class="container  d-flex justify-content-between">
                <div class="ppp">Patent</div>
                <input class="form-check-input" type="radio" name="reports" id="patent">
            </div>
        </label>
        <label class="form-check-label p-3 mb-2" for="citation" id="smaller-container">
            <div class="container  d-flex justify-content-between">
                <div class="ppp">Citation</div>
                <input class="form-check-input" type="radio" name="reports" id="citation">
            </div>
        </label>
        <label class="form-check-label p-3 mb-2" for="copyright" id="smaller-container">
            <div class="container  d-flex justify-content-between">
                <div class="ppp">Copyright</div>
                <input class="form-check-input" type="radio" name="reports" id="copyright">
            </div>
        </label>
        <label class="form-check-label p-3 mb-2" for="rift" id="smaller-container">
            <div class="container  d-flex justify-content-between">
                <div class="ppp">Candidate for Rift</div>
                <input class="form-check-input" type="radio" name="reports" id="rift">
            </div>
        </label>

        <div class="container mt-3">
            <div class="row d-flex justify-content-between align-items-end">
                <div class="col-lg-2 col-sm-12">
                    <label class="form-label" for="start_date">Start Date</label>
                    <input class="form-control mb-3" type="date" id="start_date" placeholder="Start Date">
                </div>
                <div class="col-lg-2 col-sm-12">
                    <label class="form-label" for="end_date">End Date</label>
                    <input class="form-control mb-3" type="date" id="end_date" placeholder="End Date">
                </div>

                <div class="col-lg-8 col-sm-12 d-flex justify-content-end align-items-end">
                    <div class="me-2">
                        <button asp-controller="Faculty" asp-action="FacultyReportGenerateReportPreview" class="report me-2 mb-3">Report Preview</button>
                    </div>
                    <div>
                        <button class="report mb-3">Generate Report</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <script src="~/js/ClusterCoordinator-Report-GenerateReport.js"></script>

</div>

ResearchManagementSystem/Views/Faculty/FacultyReportRecentReportPreview.cshtml
@{
    ViewData["Title"] = "Report";
    Layout = "Faculty_Layout";
}
<link href="~/css/ClusterCoordinator-Report-GenerateReport-Preview.css" rel="stylesheet" />
<div>
    <!--navbar-->
    <div class="nnvb container mt-3 mb-3">
        <div class="row">
            <div class="itm col-lg-2 col-sm-12 me-2 p-1 mb-1 text-center">
                <a class="text-decoration-none" asp-controller="Faculty" asp-action="FacultyReportGenerateReport" id="inaactive">Generate Report</a>
            </div>
            <div class="itm-active col-lg-2 col-sm-12 me-2 p-1 mb-1 text-center">
                <a class="text-decoration-none" asp-controller="Faculty" asp-action="FacultyReportRecentReport" id="aactive">Recent Report</a>
            </div>
            <div class="itm col-lg-2 col-sm-12 me-2 p-1 mb-1 text-center">
                <a class="text-decoration-none" asp-controller="Faculty" asp-action="FacultyReportArchivedReport" id="inaactive">Archived Report</a>
            </div>
        </div>
    </div>

    <!--input fields-->
    <div class="container shadow h4 p-4 mb-3" id="title">
        Report Preview
    </div>
    <div class="container p-4 mb-3 text-center" id="title">
        File Preview
    </div>
    <div class="container p-2 mb-3 text-center">
        <strong>Report Content:</strong> This is a preview of the [selected report type] report from [start date] to [end date].
    </div>
    <div class="container d-flex flex-column">
        <div class="row d-flex justify-content-end align-items-end">
            <div class="col-lg-8 col-sm-12 d-flex justify-content-end align-items-end">
                <div class="me-2">
                    <button class="report me-2 mb-3">Export as PDF</button>
                </div>
                <div>
                    <button class="report mb-3">Export as Excel</button>
                </div>
            </div>
        </div>
    </div>


</div>