ResearchManagementSystem/Models/AddFAQs.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ResearchManagementSystem.Models
{
    public class AddFAQs
    {
        [Key]
        public string FAQ_id { get; set; }

        [ForeignKey(nameof(superadmin))]
        [Display(Name = "Added by:")]
        public string? added_by { get; set; }

        public ApplicationUser? superadmin { get; set; }

        [Display(Name = "Question:")]
        public string? question_id { get; set; }
        [Display(Name = "Answer:")]
        public string? answer_id { get; set; }

    }
    public class AddReview
    {
        [Key]
        public string review_id { get; set; }

        [ForeignKey(nameof(user_name_id))]
        [Display(Name = "User Name")]
        public string? username_id { get; set; }

        public ApplicationUser? user_name_id { get; set; }

        public int? rating { get; set; }
        public string? comment { get; set; }
        public DateTime? date_posted { get; set; }
        public string? response { get; set; }
        public DateTime? response_date { get; set; }


    }
}

ResearchManagementSystem/Controllers/AddFAQsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ResearchManagementSystem.Data;
using ResearchManagementSystem.Models;
using ResearchManagementSystem.Services;

namespace ResearchManagementSystem.Controllers
{
    public class AddFAQsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserService _userService;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ApplicationDbContext _context;


        public AddFAQsController(UserManager<ApplicationUser> userManager, RoleManager<IdentityRole> roleManager, UserService userService, SignInManager<ApplicationUser> signInManager, ApplicationDbContext context)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _userService = userService;
            _signInManager = signInManager; // Initialize SignInManager
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            // Get the current user
            var user = await _userManager.GetUserAsync(User);

            // Get the roles of the current user
            var roles = await _userManager.GetRolesAsync(user);

            // Conditionally set the layout based on the user's role
            string layout;
            if (roles.Contains("SuperAdmin"))
            {
                layout = "SuperAdmin_Layout";
                ViewData["UserRole"] = "SuperAdmin";
            }
            else if (roles.Contains("Faculty"))
            {
                layout = "Faculty_Layout";
                ViewData["UserRole"] = "Faculty";
            }
            else if (roles.Contains("Student"))
            {
                layout = "Student_Layout";
                ViewData["UserRole"] = "Student";
            }
            else if (roles.Contains("RMCC"))
            {
                layout = "RMCC_Layout";
                ViewData["UserRole"] = "RMCC";
            }
            else
            {
                layout = "Director_Layout";
                ViewData["UserRole"] = "Director";
            }

            ViewData["Layout"] = layout;

            // Return the view with the appropriate layout
            return View(await _context.FAQs.ToListAsync());
        }
        // GET: AddFAQs/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var faq = await _context.FAQs
                .Include(f => f.superadmin)
                .FirstOrDefaultAsync(m => m.FAQ_id == id);
            if (faq == null)
            {
                return NotFound();
            }

            return View(faq);
        }

        // GET: AddFAQs/Create
        //[Authorize(Roles = "SuperAdmin")]
        public IActionResult Create()
        {
            ViewData["added_by"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: AddFAQs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Create([Bind("question_id, answer_id")] AddFAQs addFAQs)
        {
            addFAQs.FAQ_id = Guid.NewGuid().ToString();
            addFAQs.added_by = User.FindFirstValue(ClaimTypes.NameIdentifier);

            _context.Add(addFAQs);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        // GET: AddFAQs/Edit/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var addFAQs = await _context.FAQs.FindAsync(id);
            if (addFAQs == null)
            {
                return NotFound();
            }
            ViewData["added_by"] = new SelectList(_context.Users, "Id", "Id", addFAQs.added_by);
            return View(addFAQs);
        }

        // POST: AddFAQs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Edit(string id, [Bind("FAQ_id,added_by,question_id,answer_id")] AddFAQs addFAQs)
        {
            if (id != addFAQs.FAQ_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(addFAQs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AddFAQsExists(addFAQs.FAQ_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["added_by"] = new SelectList(_context.Users, "Id", "Id", addFAQs.added_by);
            return View(addFAQs);
        }

        // GET: AddFAQs/Delete/5
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var addFAQs = await _context.FAQs
                .Include(a => a.superadmin)
                .FirstOrDefaultAsync(m => m.FAQ_id == id);
            if (addFAQs == null)
            {
                return NotFound();
            }

            return View(addFAQs);
        }

        // POST: AddFAQs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "SuperAdmin")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var addFAQs = await _context.FAQs.FindAsync(id);
            if (addFAQs != null)
            {
                _context.FAQs.Remove(addFAQs);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AddFAQsExists(string id)
        {
            return _context.FAQs.Any(e => e.FAQ_id == id);
        }
    }
}

ResearchManagementSystem/Views/AddFAQs/Create.cshtml
@model ResearchManagementSystem.Models.AddFAQs

@{
    ViewData["Title"] = "Create";
}
<link href="~/css/SystemAdministrator-FAQs.css" rel="stylesheet" />

<div>


    <!--input fields-->
    <div class="container shadow mt-4" id="content">
        <div class="row shadow-sm display-6 p-4 mb-1" id="title">
            Add FAQ
        </div>
        <div class="row shadow p-4" id="formcont">
            <form asp-action="Create">
                <div class="row">
                    <div class="col-lg-12 col-sm-12">
                        <div class="form-group">
                            <label asp-for="FAQ_id" class="control-label"></label>
                            <input asp-for="FAQ_id" class="form-control mb-3" />
                            <span asp-validation-for="FAQ_id" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 col-sm-12">
                        <div class="form-group">
                            <label asp-for="added_by" class="control-label"></label>
                            <select asp-for="added_by" class="form-control mb-3" asp-items="ViewBag.added_by"></select>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12 col-sm-12">
                        <div class="form-group">
                            <label asp-for="question_id" class="control-label"></label>
                            <input asp-for="question_id" class="form-control mb-3" />
                            <span asp-validation-for="question_id" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12 col-sm-12">
                        <div class="form-group">
                            <label asp-for="answer_id" class="control-label"></label>
                            <input asp-for="answer_id" class="form-control mb-3" />
                            <span asp-validation-for="answer_id" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row mt-3">
                    <div class="col-lg-12 col-sm-12 d-flex justify-content-end">
                        <input type="submit" value="Create">
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!---->
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ResearchManagementSystem/Views/AddFAQs/Delete.cshtml
@model ResearchManagementSystem.Models.AddFAQs

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AddFAQs</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.superadmin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.superadmin.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.question_id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.question_id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.answer_id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.answer_id)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="FAQ_id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ResearchManagementSystem/Views/AddFAQs/Details.cshtml
@model ResearchManagementSystem.Models.AddFAQs

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>AddFAQs</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.superadmin)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.superadmin.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.question_id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.question_id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.answer_id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.answer_id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FAQ_id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ResearchManagementSystem/Views/AddFAQs/Edit.cshtml
@model ResearchManagementSystem.Models.AddFAQs

@{
    ViewData["Title"] = "Edit";
}
<link href="~/css/SystemAdministrator-FAQs.css" rel="stylesheet" />
<!--input fields-->
<div class="container shadow mt-4" id="content">
    <div class="row shadow-sm display-6 p-4 mb-1" id="title">
        Edit FAQ
    </div>
    <div class="row shadow p-4" id="formcont">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FAQ_id" />
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <div class="form-group">
                        <label asp-for="added_by" class="control-label"></label>
                        <select asp-for="added_by" class="form-control mb-3" asp-items="ViewBag.added_by"></select>
                        <span asp-validation-for="added_by" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <div class="form-group">
                        <label asp-for="question_id" class="control-label"></label>
                        <input asp-for="question_id" class="form-control mb-3" />
                        <span asp-validation-for="question_id" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <div class="form-group">
                        <label asp-for="answer_id" class="control-label"></label>
                        <input asp-for="answer_id" class="form-control mb-3" />
                        <span asp-validation-for="answer_id" class="text-danger"></span>
                    </div>
                </div>
            </div>

            <div class="row mt-3">
                <div class="col-lg-12 col-sm-12 d-flex justify-content-end">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>

        </form>
    </div>
</div>
<!---->
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ResearchManagementSystem/Views/AddFAQs/Index.cshtml
@model IEnumerable<ResearchManagementSystem.Models.AddFAQs>

@{
    ViewData["Title"] = "Index";


    Layout = ViewData["Layout"]?.ToString();  // Dynamically set the layout based on the controller
}



<link href="~/css/SystemAdministrator-FAQs.css" rel="stylesheet" />
<style>
    .action {
        border: none;
        background: none;
        border-radius: 10px;
        padding: 10px;
    }

        .action:hover {
            background: rgba(133, 0, 0, 0.2);
        }
</style>

<div>
    <div class="container d-flex justify-content-between align-items-end">
        <div class="display-6 mt-5 p-0">
            <div id="task">Frequently Asked Questions</div>
        </div>
        <div>
            <!-- Add FAQ button only for SuperAdmin -->
            <a role="button" class="btn btn-lg btn-danger admin-only" asp-controller="AddFAQs" asp-action="Create">
                Add FAQ
            </a>
        </div>
    </div>

    @{
        var faqIndex = 0; // Initialize a counter for unique IDs
    }
    @foreach (var item in Model)
    {
        <div class="container mt-3">
            <div class="container shadow p-3" id="content">
                <div class="row align-items-center">
                    <div class="lab col-10">
                        @Html.DisplayFor(modelItem => item.question_id)
                    </div>
                    <div class="col-2 text-end">
                        <button class="action" type="button" data-bs-toggle="collapse" data-bs-target="#faqcont-@faqIndex" aria-expanded="false" aria-controls="faqcont-@faqIndex">
                            <i class="fa-solid fa-circle-chevron-down fa-2xl" style="color: #850000;"></i>
                        </button>
                    </div>
                </div>
            </div>

            <div class="collapse mt-3 bg-transparent" id="faqcont-@faqIndex">
                <div class="card card-body container p-3">
                    <form>
                        <div class="row">
                            <div class="col-lg-12 col-sm-12">
                                @Html.DisplayNameFor(model => model.superadmin)
                                @Html.DisplayFor(modelItem => item.superadmin.Id)
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 col-sm-12">
                                @Html.DisplayNameFor(model => model.question_id)
                                @Html.DisplayFor(modelItem => item.question_id)
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 col-sm-12">
                                @Html.DisplayNameFor(model => model.answer_id)
                                @Html.DisplayFor(modelItem => item.answer_id)
                            </div>
                        </div>
                        <div class="row mt-3">
                            <div class="col-lg-12 col-sm-12 d-flex justify-content-end">
                                <!-- Edit and Delete buttons only for SuperAdmin -->
                                <a role="button" class="action admin-only" asp-action="Edit" asp-route-id="@item.FAQ_id">
                                    <i class="fa-solid fa-pen-to-square fa-2xl" style="color: #850000;"></i>
                                </a>
                                <a role="button" class="action admin-only" asp-action="Delete" asp-route-id="@item.FAQ_id">
                                    <i class="fa-solid fa-trash fa-2xl" style="color: #850000;"></i>
                                </a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        faqIndex++; // Increment counter for unique IDs
    }
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Get the user role from ViewData
        const userRole = '@ViewData["UserRole"]';

        // Toggle visibility of buttons based on the role
        if (userRole !== 'SuperAdmin') {
            // Hide Create, Edit, and Delete buttons for non-SuperAdmin users
            document.querySelectorAll(".admin-only").forEach(function (button) {
                button.style.display = "none";
            });
        }
    });
</script>